# Generated by Django 5.2.17 on 2026-08-19 21:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_sire_name', models.CharField(blank=True, help_text='Name/ID of sire, only if not one of your own registered goats.', max_length=120)),
                ('mating_date', models.DateField()),
                ('expected_kidding_date', models.DateField(blank=True, help_text='Auto-filled from mating date (~150 days) if left blank.', null=True)),
                ('actual_kidding_date', models.DateField(blank=True, null=True)),
                ('litter_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('had_complications', models.BooleanField(default=False)),
                ('complication_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('father', models.ForeignKey(blank=True, help_text='Leave blank if using an external/borrowed sire — use the field below instead.', limit_choices_to={'sex': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breeding_as_father', to='core.goat')),
                ('mother', models.ForeignKey(limit_choices_to={'sex': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='breeding_as_mother', to='core.goat')),
            ],
            options={
                'ordering': ['-mating_date'],
            },
        ),
        migrations.CreateModel(
            name='FeedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('feed_type', models.CharField(help_text='e.g. hay, grain mix, silage, browse', max_length=100)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goat', models.ForeignKey(blank=True, help_text='Leave blank if this feed record is for the whole herd rather than one goat.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_records', to='core.goat')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('symptoms', models.TextField(blank=True, help_text='Any observed symptoms, or leave blank if none.')),
                ('is_sick', models.BooleanField(default=False, help_text='Mark true if this goat is currently unwell.')),
                ('vaccinated', models.BooleanField(default=False)),
                ('vaccine_name', models.CharField(blank=True, max_length=120)),
                ('vet_visit', models.BooleanField(default=False)),
                ('vet_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='core.goat')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MilkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('yield_liters', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='core.goat')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('goat', 'date')},
            },
        ),
    ]
