# Generated by Django 5.2.17 on 2026-08-20 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goat',
            name='ear_tag_number',
            field=models.CharField(blank=True, help_text='The physical ear tag ID on this goat, e.g. HGF-014. Leave blank if not tagged yet.', max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='goat',
            name='father',
            field=models.ForeignKey(blank=True, limit_choices_to={'sex': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_as_father', to='core.goat'),
        ),
        migrations.AddField(
            model_name='goat',
            name='mother',
            field=models.ForeignKey(blank=True, limit_choices_to={'sex': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_as_mother', to='core.goat'),
        ),
    ]
