# Generated by Django 5.2.17 on 2026-08-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_goat_ear_tag_number_goat_father_goat_mother'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
