# Generated by Django 5.2.17 on 2026-08-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_blogpost_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('video_url', models.URLField(blank=True, help_text='Optional. A YouTube link — embeds automatically.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first.')),
                ('is_featured', models.BooleanField(default=True, help_text='Show on the homepage.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_heading', models.CharField(default='Raised with care, in the heart of the hills.', max_length=200)),
                ('hero_subheading', models.TextField(default='Ethically raised goats, fresh milk, and quality breeding stock — straight from our family farm to you.')),
                ('hero_image', models.ImageField(blank=True, help_text='Shown as the hero background if no video link is set below.', null=True, upload_to='homepage/')),
                ('hero_video_url', models.URLField(blank=True, help_text='Optional. Paste a YouTube link (any format) to show a video instead of the image — it embeds automatically.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Page',
            },
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(default='About Himal Goat Farm', max_length=200),
        ),
    ]
